### ISSUE TITLE
Broken State

### ISSUE THREAD

**Issue by kvmanohar22** [ros-arch/ros-build-tools#3]
This package seems to be in a broken state.

I am trying to install `ros-melodic-ros-base` and the build fails with the following error:

```
==> Starting build()...
/home/kv/.cache/yay/ros-melodic-smclib/PKGBUILD: line 43: /usr/share/ros-build-tools/fix-python-scripts.sh: No such file or directory
==> ERROR: A failure occurred in build().
    Aborting...
error making: ros-melodic-smclib

```
The contents of the installed `ros-build-tools` is as follows:

```
[kv@xps ~]$ ls /usr/share/ros-build-tools/
clear-ros-env.sh
[kv@xps ~]$ 
```
It is clearly missing some of the required files such as `fix-python-version.sh`. Based on the git log I can see this file was present in the earlier versions of this repo but got removed.

My doubt is, should the removed files be reintroduced or is there something wrong that I am doing?

**Comment by acxz** [comment]
Hello @kvmanohar22! Sorry you had to run into this issue, but unfortunately ros-melodic is end of life.
See: http://wiki.ros.org/Distributions

As such `ros-melodic-*` packages are not supported on Arch Linux. If you need to use ros on Arch Linux, I urge you to use the Noetic distribution, i.e. the `ros-noetic-*` packages.

**Comment by acxz** [comment]
If you have any issues with those packages, be sure to file your issue at the github repo for that package. I'll close this issue for now, and if you have any other issues regarding this particular package than go ahead and open up another issue here.
